import { ScanResult } from '../types';

export const MOCK_RESULT: ScanResult = {
  scan_id: "A3F8C2D1",
  filename: "suspicious_loader.exe",
  threat_level: "MALICIOUS",
  confidence_score: 0.891,
  detection_path: "LLM_HEURISTIC",
  yara_result: { matched: false, matched_rules: [] },
  llm_analysis: {
    verdict: "MALICIOUS",
    reasoning: "The binary exhibits high Shannon entropy (7.45) consistent with a custom packer, combined with 8 suspicious API imports including VirtualAlloc and CreateRemoteThread. Anti-debugging calls and network C2 indicators strongly suggest a staged loader payload.",
    behavioral_flags: [
      "High entropy 7.45 — likely packed",
      "CreateRemoteThread detected — process injection",
      "URLDownloadToFile — remote payload fetch",
      "IsDebuggerPresent — anti-analysis evasion",
      "PE timestamp spoofed"
    ]
  },
  generated_yara_rule: `rule SentinelX_AutoGen_A3F8C2D1 {
    meta:
        description = "Auto-generated by SentinelX v2.0"
        author      = "SentinelX AI Engine"
        date        = "2026-03-13"
    strings:
        $anti_debug1 = "IsDebuggerPresent" ascii
        $net1 = "URLDownloadToFile" ascii
    condition:
        uint16(0) == 0x5A4D and
        math.entropy(0, filesize) >= 7.0 and
        any of them
}`,
  recommendation: "BLOCK immediately. Quarantine file and isolate endpoint.",
  processing_time_ms: 284,
  ts: new Date().toLocaleTimeString()
};

export const generateMockScan = (filename: string): ScanResult => {
  const threats: ('MALICIOUS' | 'SUSPICIOUS' | 'SAFE')[] = ['MALICIOUS', 'SUSPICIOUS', 'SAFE'];
  const threat = threats[Math.floor(Math.random() * threats.length)];
  const scanId = Math.random().toString(36).substring(2, 10).toUpperCase();
  
  const configs = {
    MALICIOUS: {
      confidence: 0.75 + Math.random() * 0.24,
      path: Math.random() > 0.5 ? 'YARA_STATIC' : 'LLM_HEURISTIC',
      yaraMatched: Math.random() > 0.5,
      recommendation: "BLOCK immediately. Quarantine file and isolate endpoint.",
      reasoning: "The binary exhibits high Shannon entropy consistent with a custom packer, combined with suspicious API imports. Anti-debugging calls and network C2 indicators suggest malicious intent.",
      flags: ["High entropy — likely packed", "Suspicious API imports", "Anti-debugging techniques", "Network indicators"]
    },
    SUSPICIOUS: {
      confidence: 0.45 + Math.random() * 0.29,
      path: 'LLM_HEURISTIC',
      yaraMatched: false,
      recommendation: "QUARANTINE — Hold for further analysis. Do not execute.",
      reasoning: "The file shows some anomalous characteristics but does not match known malware signatures. Manual review recommended before allowing execution.",
      flags: ["Unusual section names", "Elevated entropy", "Uncommon compiler signature"]
    },
    SAFE: {
      confidence: 0.85 + Math.random() * 0.14,
      path: Math.random() > 0.7 ? 'YARA_STATIC' : 'LLM_HEURISTIC',
      yaraMatched: false,
      recommendation: "CLEAR — File appears benign.",
      reasoning: "No malicious indicators detected. File structure and behavior patterns consistent with legitimate software.",
      flags: []
    }
  };

  const config = configs[threat];

  return {
    scan_id: scanId,
    filename,
    threat_level: threat,
    confidence_score: config.confidence,
    detection_path: config.path,
    yara_result: { 
      matched: config.yaraMatched, 
      matched_rules: config.yaraMatched ? ['Packed_Binary', 'Suspicious_Import'] : [] 
    },
    llm_analysis: {
      verdict: threat,
      reasoning: config.reasoning,
      behavioral_flags: config.flags
    },
    generated_yara_rule: threat === 'MALICIOUS' ? `rule SentinelX_AutoGen_${scanId} {
    meta:
        description = "Auto-generated by SentinelX v2.0"
        author      = "SentinelX AI Engine"
        date        = "${new Date().toISOString().split('T')[0]}"
    strings:
        $suspicious1 = "VirtualAlloc" ascii
        $suspicious2 = "CreateRemoteThread" ascii
    condition:
        uint16(0) == 0x5A4D and any of them
}` : null,
    recommendation: config.recommendation,
    processing_time_ms: 150 + Math.floor(Math.random() * 200),
    ts: new Date().toLocaleTimeString()
  };
};
